version: '3'

services:

  postgres:
    image: postgres:13.4
    container_name: utfinquadra-api-postgres
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=utfinquadra
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: utfinquadra-api-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ingresso.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80